###
GET http://{{host}}/api/product
Accept: application/json

###
GET http://{{host}}/api/product/4
Accept: application/json

###
POST http://{{host}}/api/product
Content-Type: application/json

{
  "title": "1234",
  "description": "descriptiondescription"
}

###
PUT http://{{host}}/api/product
Content-Type: application/json

{
  "id": 4,
  "title": "1234",
  "description": "descriptiondescription"
}

